### ISSUE TITLE
Multiplication is missing

### ISSUE THREAD

**Issue by jadephilipoom** [mit-plv/bedrock2#139]
I tried to bump the version of bedrock2 used by the fiat-crypto backend I'm developing, and found that all forms of multiplication have been eliminated from the binary operations in `Syntax.v`. 

The commit comment (e66c30) explains that this is in order to limit instructions to RV32I and RV64I, which indeed don't have multiply, so I see the reasoning. However, this limitation would make the fiat-crypto backend impossible. Are there any plans to add the RVM extension (the one that contains multiplication)? And, if the answer is "eventually", is there something we can do in the meantime to maintain compatibility other than me just never bumping the submodule?

**Comment by samuelgruetter** [comment]
Yeah I saw that coming... The right thing to do would be to abstract over the type of binary operators, or to add a check which rules out multiplication in the source, or to add a flag to the semantics -- in any case, adding a new abstraction, and we've had a bit too many abstractions in this project recently, which slowed down the development.

On the other hand, I really want to stay "reasonably compatible" with your work, so I do appreciate that you want to update your bedrock2 submodule to our latest version. So as a middle ground solution for the moment, maybe we could just have two copies of `Syntax.v` and `Semantics.v`, both on our `master` branch, so both copies stay (kind of) in sync with the bedrock2 developments, and once the fiat-crypto backend is ready to be connected to bedrock2, we introduce the abstraction needed for this to make it work?

**Comment by jadephilipoom** [comment]
The impetus for me to update is actually https://github.com/coq/coq/pull/11530 -- until I bump bedrock2 to a later version, Coq's build of fiat-crypto is failing. Is there an intermediate commit I could bump to that could fix this issue without breaking due to lack of multiplication?

In the long term, I see a couple of options:
1. Depend on an old version of bedrock2 until the backend is ready. Due to the Coq test, I think this would require factoring the backend into a new repository that depends on fiat-crypto and bedrock2.
2. As Sam suggests, keeping two copies of `Syntax` and `Semantics` in bedrock2. But will the second version connect to any proofs? It seems like it would add a burden to bedrock2 development, and I'm not sure it's an improvement over depending on an old version.

**Comment by samuelgruetter** [comment]
If you start depending on an intermediate commit, you'll have to backport fixes we make in order to stay compatible with coq master, and we'll have to maintain two branches -- doesn't sound great to me.

But here's an idea: Originally I aimed for a total compiler (which, given some preconditions, always outputs a valid riscv program), but by now, I'm ok with having a partial compiler until we finish a first end-to-end Qed. Originally I wrote proofs that encode-then-decode for any compiler-emitted riscv instruction yields back the original instruction, but these would need quite some updating now, so instead, I'll use a more translation-validation-like approach: I'll just test if encode-then-decode returns the same list of instructions for the concrete program I'm about to compile, and return `None` if not. The decode in this encode-then-decode test will use RV32I for lightbulb and RV32IM for fiat-crypto, making this an option should be easy. In particular, if there were multiplications in the source program, this test will fail in the lightbulb setting, but since it works right now where all multiplication was removed, it will keep working if I add back multiplication.

So I took a quick look at what it would take to add back multiplication right now, and it was so easy that I just did it: https://github.com/mit-plv/bedrock2/commit/b28c1dc5e2c35238acb05cd0aed67176afaa71b6

**Comment by jadephilipoom** [comment]
Amazing, thanks!

In case this comes up again, I'll leave the note that Jason says we could have Coq's test do a partial build, ignoring the bedrock2 backend and its dependencies, which is in fact a better option than any I listed and should be the starting point if there's a next time.
