### ISSUE TITLE
Platform

### ISSUE THREAD

**Issue by spitters** [mit-plv/bedrock2#176]
Inclusion in platform will aid easy installation on all OSes:
https://github.com/coq/platform

**Comment by samuelgruetter** [comment]
Are you suggesting that bedrock2 should be part of the Coq platform? As far as I understand, the Coq platform is supposed to only contain somewhat stable, mature and easy to use packages which are ready for use by a wider audience, and I think bedrock2 clearly has not yet reached that point. Or in other words: Someone who is experienced enough to deal with the rough edges currently present in bedrock2 is certainly also experienced enough to install bedrock2 on any OS.

**Comment by spitters** [comment]
@samuelgruetter you may be right. We're depending on the bedrock2 for our work in Aarhus. If you can find two other projects, bedrock2 qualifies for inclusion:
https://github.com/coq/platform/blob/2021.02/charter.md#package-inclusion-process

As a rule, it simplifies our life to have our dependencies (in this case bedrock2) in platform.

Perhaps related to the CI issue:
https://github.com/mit-plv/bedrock2/issues/170

**Comment by samuelgruetter** [comment]
I'm not sure if it would actually simplify your life, because anyone trying to use bedrock2 still encounters issues (eg https://github.com/mit-plv/bedrock2/issues/175) that need to get fixed in order for them to continue working on their project.
Now, if someone was using bedrock2 through the Coq platform, they would have to wait for a new release of the Coq platform to get the fix, which might take a long time. On the other hand, if they include bedrock2 as a git submodule, they can just `git pull` to obtain the fix immediately.

**Comment by spitters** [comment]
You may be right, that this is premature. Thanks for the great work on bedrock2.
