### ISSUE TITLE
record for language parameters

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#3]
I think it would be an improvement to have ExprImp and FlatImp parametrized over something of a type like the following:

~~~~~~~~~~~~
Record LanguageParameters :=
{ 
  Bw: RiscvBitWidths;
  Name: NameWithEq;
  var := name Name;
  FName : NameWithEq.
  func := (@name FName);
  state: Type;
  stateMap: Map state var (word wXLEN);
}.
~~~~~~~~~~~~

Othwerwise typeclass resultion picks up some arbitrary instantiation of this unless care is taken to do otherwise, making stating general theorems rather difficult.

**Comment by samuelgruetter** [comment]
Assuming you meant to delete these two lines:

```
  var := name Name;
  func := (@name FName);
```

Sounds like a good idea, as long as `LanguageParameters` does not turn into a god object. In particular, nothing RiscV-specific should creep in (`RiscvBitWidths` is an exception because it's not directly related to RiscV, and I was planning to rename it, but just haven't done so yet).

**Comment by andres-erbsen** [comment]
This is happening already, `bedrock2.Syntax.parameters`
