### ISSUE TITLE
consolidate and factor out map library

### ISSUE THREAD

**Issue by andres-erbsen** [mit-plv/bedrock2#33]
a proper fix for `reduce_locals_map` would require nontrivial Ltac development that would depend on the exact shape of map definitions, and I don't want to do this before we have some tentatively acceptable definitions to go on with.

**Comment by andres-erbsen** [comment]
@samuelgruetter are there any operations that you still think should be a part of the map interface but are not yet in https://github.com/mit-plv/bedrock2/blob/master/bedrock2/src/Map.v#L2 ?

**Comment by samuelgruetter** [comment]
Naming:
*   I'd prefer `update_map` over `union` because `union` suggests that it's commutative

Missing:
*   `restrict: map -> set K -> map`
*   `domain: map -> set K`
*   `range: map -> set V`
*   `reverse_get: map -> V -> option K`
*   `intersect_map: map -> map -> map`
*   `remove_keys: map -> set K -> map`
*   `remove_by_value: map -> V -> map`
*   `remove_values: map -> set V -> map`
*    maybe `filter: map -> (K -> V -> bool) -> map`

but if some of these operations make an implementation you would like impossible, I'm ok adding the extra operations in a subclass.
Also, as you said, `remove_keys`, `remove_values`, and `restrict` could probably be implemented with `filter`, so maybe `filter` should be added too?

**Comment by samuelgruetter** [comment]
> `update` is commonly used for a different operation `K -> V -> (K -> V -> V) -> map -> map`.

how about `update_with`? or anything other different from `update` and `union`?


> `remove_by_value` and `reverse_get` -- how would you implement them in a function-based map? 

I gave up on function-based maps, because concrete values are too hard to read and get too big, and don't support `domain` and `range`, so the anwer is: not at all

> and which key should it return?
> 

`remove_by_value` removes all tuples matching the value, while `reverse_get` returns any key with the given value

> `intersect_map` -- do you have an implementation in mind that would specialize it? otherwise we could define it on top of the map like `putmany`.
> 

I don't have a specialized implementation in mind, but if you want to implement it outside of the interface, you'll probably need an iterator for maps, which I didn't have so far, but with `filter` I guess it would work.

> The others take `set` and thus do not belong in a map library.

but in a "set and map" library, which I eventually will need :wink:

**Comment by andres-erbsen** [comment]
This is now in https://github.com/mit-plv/coqutil/blob/master/src/Map/Interface.v
